const fs = require('fs');

const viewModel = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/ui/BrowserViewModel.kt', 'utf8');
const screen = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/ui/BrowserScreen.kt', 'utf8');
const controls = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/ui/BrowserControls.kt', 'utf8');
const sheets = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/ui/BrowserSheets.kt', 'utf8');
const models = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/data/BrowserModels.kt', 'utf8');
const repository = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/data/BrowserRepository.kt', 'utf8');
const webView = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/web/BrowserWebView.kt', 'utf8');
const mainActivity = fs.readFileSync('app/src/main/java/com/example/httpsbrowser/MainActivity.kt', 'utf8');
const cargoToml = fs.readFileSync('app/src/main/rust/Cargo.toml', 'utf8');
const androidCi = fs.readFileSync('.github/workflows/android-ci.yml', 'utf8');

function requireText(source, text, label) {
  if (!source.includes(text)) throw new Error(`${label}: missing ${text}`);
}
function forbidText(source, text, label) {
  if (source.includes(text)) throw new Error(`${label}: obsolete ${text} remains`);
}

requireText(viewModel, 'beginAddressEditing(if (tab.isHome) "" else tab.displayText.ifBlank { tab.url })', 'Google query focus suggestions');
requireText(viewModel, 'fun setAddressInput(value: String) = beginAddressEditing(value)', 'unified address editing');
requireText(viewModel, 'return results.values.take(MAX_SUGGESTIONS)', 'suggestion count limit');
requireText(viewModel, 'private fun fetchGoogleSuggestions(query: String)', 'bounded Google suggestion request path');
requireText(viewModel, 'finally {\n            // 検索候補は短時間に連続して要求されるため、成功・失敗・キャンセルを問わず接続を解放する。\n            connection.disconnect()\n        }', 'Google suggestion connection cleanup');
requireText(viewModel, 'if (uiState.selectedTab?.isHome == false) openHome()', 'home back fallback');
requireText(controls, 'onSubmit: (String) -> Unit', 'IME latest input contract');
requireText(controls, 'onSubmit(textFieldValue.text)', 'IME latest input call');
requireText(controls, 'onEditingStopped: () -> Unit', 'address focus loss contract');
requireText(controls, 'if (!focus.isFocused && isEditing) onEditingStopped()', 'address focus loss ends edit mode');
requireText(screen, 'onEditingStopped = viewModel::stopAddressEditing', 'screen restores controls on address focus loss');
forbidText(screen, 'OnGlobalLayoutListener', 'IME layout observer that can race address focus');
requireText(screen, 'onBackgroundTap = ::endAddressEditing', 'home background ends address editing');
requireText(controls, 'onBackgroundTap: () -> Unit', 'home background tap contract');
requireText(controls, 'reverseLayout = true', 'bottom-up suggestion layout');
forbidText(screen, 'WindowInsets.isImeVisible', 'IME visibility observer that can race address focus');
forbidText(screen, 'addressImeWasVisible', 'stale IME visibility state');
requireText(screen, 'state.isAddressFocused -> viewModel.stopAddressEditing()', 'system back ends address editing');
requireText(screen, 'onSubmit = { input -> navigate(input) }', 'IME navigation wiring');
requireText(screen, 'onOpenBookmark = { bookmark -> navigate(bookmark.url) }', 'bookmark URL-bar navigation');
requireText(screen, 'Text("共有")', 'long-pressed link share action');
requireText(screen, 'Text("ホームショートカットに追加")', 'long-pressed link shortcut action');
requireText(screen, 'title = { Text("リンクの操作") }', 'organized long-press menu title');
requireText(screen, 'Text("キャンセル")', 'organized long-press menu dismissal');
requireText(screen, 'title = "ホームショートカットに追加"', 'link shortcut editor reuse');
requireText(controls, 'Color(0xFF5E5E5E)', 'neutral gray shortcut base color');
requireText(controls, 'tab.isPrivate && selected -> Color(0xFF3D235B)', 'selected private tab purple background');
requireText(controls, 'tab.isPrivate && selected -> Modifier.border(2.dp, Color(0xFFC084FC)', 'selected private tab purple border');
requireText(controls, 'tab.isPrivate -> Color(0xFF2A1B38)', 'unselected private tab purple background');
requireText(controls, 'modifier = Modifier.size(38.dp)', 'smaller home shortcut icon');
requireText(controls, 'contentScale = ContentScale.Fit', 'favicon avoids crop enlargement');
requireText(controls, 'Modifier.fillMaxSize().padding(4.dp).clip(RoundedCornerShape(7.dp))', 'favicon uses rounded-corner inset');
requireText(controls, 'modifier.clip(RoundedCornerShape(10.dp)).background(Color(0xFF5E5E5E))', 'square favicon base is rounded');
requireText(screen, 'selectedTab?.isHome == false -> {\n                if (registry.canGoBack(selectedTab.id)) registry.goBack(selectedTab.id)\n                else returnSelectedTabToHome()\n            }', 'system back always falls through to home after WebView history is exhausted');
requireText(screen, 'val canReturnToHome = !selectedTab.isHome', 'normal-page back stays available while history callbacks are pending');
requireText(screen, 'canGoBack = canReturnToHome', 'back button does not depend on a stale history mirror');
requireText(screen, 'if (registry.canGoBack(selectedTab.id)) registry.goBack(selectedTab.id)\n                                    else returnSelectedTabToHome()', 'navigation-row falls through to home after history exhaustion');
requireText(webView, 'fun goBack(tabId: String): Boolean', 'back requests report whether they were accepted');
requireText(webView, 'fun beginBackNavigation(): Boolean', 'rapid back requests are serialized per WebView');
requireText(webView, 'queuedBackRequests = (queuedBackRequests + 1).coerceAtMost(MAX_QUEUED_BACK_REQUESTS)', 'rapid back request queue is bounded');
requireText(webView, 'if (!goBack(tabId)) entry.callbacks.onBackHistoryExhausted(tabId)', 'queued back exhaustion triggers explicit home fallback');
requireText(screen, 'override fun onBackHistoryExhausted(tabId: String)', 'only the selected tab receives queued home fallback');
forbidText(models, 'returnToHomeOnBack', 'obsolete tab-origin home fallback flag');
forbidText(repository, 'returnToHomeOnBack', 'obsolete home fallback persistence');
requireText(sheets, 'label = "広告ブロック"', 'adblock label');
requireText(sheets, 'label = "暗色化"', 'dark mode label');
requireText(sheets, 'Text(if (highSelected) "normal" else "✓ normal")', 'normal mode selection');
requireText(sheets, 'Text(if (highSelected) "✓ high" else "high")', 'high mode selection');
forbidText(sheets, '広告 URL ルールをブロック', 'renamed adblock setting');
forbidText(sheets, '攻めた広告遮断モード', 'renamed high adblock mode');
forbidText(sheets, '動画サイトにも暗色化を適用', 'renamed high dark mode');

requireText(viewModel, 'uiState = uiState.copy(addressInput = "", isAddressFocused = false, isSuggestionPanelVisible = false, suggestions = emptyList())', 'home clears address and suggestion state');
const homeReturnFunction = screen.indexOf('fun returnSelectedTabToHome()');
const homeStateUpdate = screen.indexOf('viewModel.returnSelectedTabToHome()', homeReturnFunction);
const homeOverlayHide = screen.indexOf('(activity as? MainActivity)?.hideNormalWebContent()', homeReturnFunction);
if (homeReturnFunction < 0 || homeStateUpdate < 0 || homeOverlayHide < 0 || homeStateUpdate > homeOverlayHide) {
  throw new Error('home state must clear before the retained WebView is covered');
}
requireText(screen, 'private fun shouldShowRightEdgeScrollRail(url: String): Boolean', 'Google popup scroll protection helper');
requireText(screen, 'host.startsWith("google.") || host.contains(".google.")', 'Google web surface detection');
requireText(screen, 'if (!state.isFullscreen) {', 'edge rail is available on every non-fullscreen page');
forbidText(screen, 'if (!state.isFullscreen && shouldShowRightEdgeScrollRail(selectedTab.url))', 'edge rail must not be Google-only');
requireText(screen, 'statusBarsPadding().navigationBarsPadding()', 'safe system-bar layout for page and bottom controls');
requireText(screen, 'Modifier.fillMaxWidth().imePadding().background(MaterialTheme.colorScheme.surface)', 'address bar follows the keyboard without moving the WebView host');
requireText(screen, 'reserveRightTouchRail = !isGoogleImageSurface(selectedTab.url)', 'native touch rail is disabled only for Google image details');
requireText(screen, 'placeAboveCompose = isGoogleImageSurface(selectedTab.url)', 'Google image details use direct WebView touch');
requireText(mainActivity, 'normalWebContentReservesRightTouchRail', 'page-specific native rail reservation');
requireText(mainActivity, 'else 0', 'Google web surfaces forward the full page width');
requireText(mainActivity, 'clipChildren = true', 'native host clips popup rendering to page bounds');
requireText(mainActivity, 'normalWebContentHost.bringToFront()', 'Google native front layer');
requireText(webView, 'view.bringToFront()', 'selected tab WebView is promoted without recreation');
forbidText(webView, 'host.removeAllViews()', 'tab switch must not detach the outgoing WebView');
forbidText(webView, 'host.getChildAt(index).visibility = View.INVISIBLE', 'tab switch must not hide the outgoing media surface');
requireText(mainActivity, 'normalWebContentPlacedAboveCompose', 'native host z-order is restored after an overlay');
requireText(mainActivity, 'Composeの下で表示を維持することで動画・音声の描画サーフェスと再生sessionを保つ', 'overlay keeps media surface attached');
requireText(mainActivity, 'if (visible && normalWebContentPlacedAboveCompose) normalWebContentHost.bringToFront()', 'overlay restore honors Google native front layer');
forbidText(mainActivity, 'if (visible && normalWebContentBoundsReady) View.VISIBLE else View.INVISIBLE', 'overlay must not hide the WebView surface');
requireText(mainActivity, 'ホームタブでも既存WebViewをhostから外さない', 'home tab keeps background media session attached');
forbidText(mainActivity, 'normalWebContentHost.removeAllViews()\n        // 次に通常ページへ戻る時', 'home tab must not detach media WebViews');
requireText(cargoToml, 'version = "=0.13.3"', 'Brave adblock-rust version is exactly pinned');
requireText(webView, 'WebSettingsCompat.setAlgorithmicDarkeningAllowed(view.settings, allowPlatformDarkening)', 'targetSdk 35 uses the supported algorithmic darkening API');
requireText(webView, 'override fun onScaleChanged(view: WebView, oldScale: Float, newScale: Float)', 'scale changes are captured without the deprecated WebView scale getter');
requireText(webView, 'fun scrollToBottom(tabId: String) = entries[tabId]?.webView?.pageDown(true)', 'bottom scrolling avoids the deprecated scale getter');
forbidText(webView, 'databaseEnabled = false', 'deprecated WebSQL setting');
forbidText(webView, 'WebSettingsCompat.setForceDark(', 'deprecated Force Dark setting');
forbidText(webView, 'WebSettingsCompat.setForceDarkStrategy(', 'deprecated Force Dark strategy');
forbidText(webView, '.scale', 'deprecated WebView scale getter');
requireText(mainActivity, 'override fun onPictureInPictureModeChanged(isInPictureInPictureMode: Boolean, newConfig: Configuration)', 'PiP uses the Configuration-aware callback');
forbidText(mainActivity, 'override fun onPictureInPictureModeChanged(isInPictureInPictureMode: Boolean) {', 'deprecated PiP boolean-only callback');
requireText(androidCi, 'retention-days: 3', 'short artifact retention protects Actions storage');
forbidText(androidCi, 'retention-days: 14', 'obsolete long artifact retention');

requireText(models, 'skipDarkeningAlreadyDarkPages: Boolean = false', 'already-dark exclusion default');
requireText(models, 'darkModeExcludedHosts: List<String> = emptyList()', 'manual dark exclusion model');
requireText(repository, 'skip_darkening_already_dark_pages', 'already-dark DataStore key');
requireText(repository, 'dark_mode_excluded_hosts', 'manual dark exclusion DataStore key');
requireText(sheets, '"元から暗いページでは追加暗色化しない"', 'already-dark setting UI');
requireText(sheets, 'SettingsPage.DARK_EXCLUSIONS -> DarkExclusionsPage', 'manual dark exclusion page routing');
requireText(sheets, '"暗色化の例外"', 'manual dark exclusion setting UI');
requireText(webView, 'DARK_DETECTOR_WITHOUT_OVERRIDE_SCRIPT', 'unmodified-style dark detector');
requireText(webView, 'prepareDarkDocumentStartScript(entry, url)', 'document-start dark CSS preparation');
requireText(webView, 'beginDarkRevealGuard(view, it, url)', 'black reveal guard on page start');
requireText(webView, 'beginDarkRevealGuard(entry.webView, entry, url)', 'black reveal guard before navigation');
requireText(webView, 'releaseDarkRevealGuard(view, entry, url)', 'reveal guard release');
requireText(webView, 'isDarkModeExcluded(settings, url)', 'manual dark exclusion runtime matching');
requireText(webView, 'fun refreshContentFiltering()', 'post-compile adblock reapplication');
requireText(webView, 'adblock_reapplied_after_engine_ready', 'engine-ready adblock diagnostic');
requireText(screen, 'registry.refreshContentFiltering()', 'post-compile existing tab protection');
requireText(webView, 'entry.documentIsAlreadyDark && entry.settings.skipDarkeningAlreadyDarkPages', 'existing-dark runtime suppression');
requireText(webView, 'private fun canNavigateHistory(view: WebView, direction: Int)', 'single WebView history predicate');
requireText(webView, 'fun canGoForward(tabId: String)', 'normal-page forward availability comes from WebView history');
forbidText(webView, 'homeResetInProgress', 'obsolete home history reset state');
forbidText(webView, 'fun resetForHome', 'obsolete home-specific history reset');
forbidText(webView, 'fun syncHistoryState', 'home must not synthesize WebView history state');
requireText(viewModel, 'val resumeUrl = tab.lastRequestedUrl.ifBlank { tab.url }', 'home preserves an explicit page-resume target');
requireText(viewModel, 'fun canResumeSelectedTabFromHome(): Boolean', 'home resume availability');
requireText(viewModel, 'fun resumeSelectedTabFromHome()', 'home forward resumes retained page');
requireText(screen, 'viewModel.canResumeSelectedTabFromHome()', 'home forward button reads resume availability');
requireText(screen, 'if (selectedTab.isHome) viewModel.resumeSelectedTabFromHome()', 'home forward resumes page instead of synthesizing history');
requireText(screen, 'else registry.goForward(selectedTab.id)', 'normal forward delegates to WebView history');
requireText(webView, 'isVideoPlaybackDocumentUrl(url) || isDarkModeExcluded(entry.settings, url)', 'video and manual exclusion path');
forbidText(screen, 'このページの描画プロセスが終了しました。タブを再作成しています。', 'renderer restart modal');

console.log('Browser stabilization settings, address focus recovery, serialized home back fallback, retained home forward history, shortcut UI, long-press actions, Google popup scrolling, safe bounds, renderer notice removal, and dark-page exclusion: OK');
